apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdockerfileimage
  template:
    metadata:
      labels:
        app: testdockerfileimage
    spec:
      containers:
      - image: localhost:5001/testdockerfile-php
        name: testdockerfileimage
        ports:
          - containerPort: 84
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: phpweb
spec:
  selector:
    app: phpweb
  ports:
    - port: 84
      targetPort: 84
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadbimage
  template:
    metadata:
      labels:
        app: mariadbimage
    spec:
      containers:
      - image: localhost:5001/mariadb
        name: mariadbimage
        ports:
          - containerPort: 3306
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginximage
  template:
    metadata:
      labels:
        app: nginximage
    spec:
      containers:
      - image: localhost:5001/nginx
        name: nginximage
        ports:
          - containerPort: 9000
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 9000
      targetPort: 9000