version: '3.8'
name: php-learning
services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: PHP-Web
        volumes:
            - ./www:/var/www/html
        restart: always

    web:
        image: nginx:latest
        container_name: PHP-Nginx
        ports:
            - "84:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www/html
        restart: always
        depends_on:
            - app

    mysql:
        image: mysql:5.7
        container_name: PHP-Mysql
        environment:
            MYSQL_DATABASE: php_learning # tên data đây là database mặc định khi tạo csdl
            MYSQL_ROOT_PASSWORD: khang412 # password gốc
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3311:3306
        restart: always